export const DASHBOARD_SECTION_GROUPS = [
    {
        key: 'executive',
        label: 'Executive',
        sections: ['overview', 'revenue', 'reports'],
    },
    {
        key: 'operations',
        label: 'Operations',
        sections: ['properties', 'bookings', 'maintenance', 'inquiries'],
    },
    {
        key: 'finance',
        label: 'Finance',
        sections: ['contracts', 'invoices', 'payments'],
    },
    {
        key: 'people',
        label: 'People',
        sections: ['customers', 'agents', 'tenants'],
    },
    {
        key: 'system',
        label: 'System',
        sections: ['notifications', 'activity', 'roles', 'settings'],
    },
];

export const DASHBOARD_SECTIONS = {
    overview: {
        key: 'overview',
        label: 'Overview',
        icon: 'pi pi-th-large',
        description: 'KPI cards, property highlights, and platform snapshot',
        component: 'OverviewSection',
    },
    revenue: {
        key: 'revenue',
        label: 'Revenue',
        icon: 'pi pi-chart-line',
        description: 'Revenue trends, collections, and growth analytics',
        component: 'RevenueSection',
    },
    properties: {
        key: 'properties',
        label: 'Properties',
        icon: 'pi pi-building',
        description: 'Manage listings, availability, and property performance',
        component: 'PropertiesSection',
        adminRoute: '/admin/rooms',
    },
    customers: {
        key: 'customers',
        label: 'Customers',
        icon: 'pi pi-users',
        description: 'Resident and owner account management',
        component: 'CustomersSection',
        adminRoute: '/admin/residents',
    },
    agents: {
        key: 'agents',
        label: 'Agents',
        icon: 'pi pi-id-card',
        description: 'Sales and leasing agent performance',
        component: 'AgentsSection',
        adminRoute: '/admin/staff',
    },
    tenants: {
        key: 'tenants',
        label: 'Tenants',
        icon: 'pi pi-user',
        description: 'Active tenant leases and occupancy',
        component: 'TenantsSection',
        adminRoute: '/admin/residents',
    },
    inquiries: {
        key: 'inquiries',
        label: 'Inquiries',
        icon: 'pi pi-inbox',
        description: 'Inbound requests and follow-up queue',
        component: 'InquiriesSection',
    },
    contracts: {
        key: 'contracts',
        label: 'Contracts',
        icon: 'pi pi-file',
        description: 'Sale and rent contract pipeline',
        component: 'ContractsSection',
        adminRoute: '/admin/sale-contracts/active',
    },
    invoices: {
        key: 'invoices',
        label: 'Invoices',
        icon: 'pi pi-receipt',
        description: 'Issued, partial, and overdue billing',
        component: 'InvoicesSection',
        adminRoute: '/admin/invoices',
    },
    payments: {
        key: 'payments',
        label: 'Payments',
        icon: 'pi pi-wallet',
        description: 'Payment approvals and reconciliation',
        component: 'PaymentsSection',
        adminRoute: '/admin/payments',
    },
    bookings: {
        key: 'bookings',
        label: 'Bookings',
        icon: 'pi pi-calendar',
        description: 'Viewings, reservations, and scheduling',
        component: 'BookingsSection',
    },
    maintenance: {
        key: 'maintenance',
        label: 'Maintenance',
        icon: 'pi pi-wrench',
        description: 'Work orders and facility requests',
        component: 'MaintenanceSection',
        adminRoute: '/admin/maintenance-requests',
    },
    notifications: {
        key: 'notifications',
        label: 'Notifications',
        icon: 'pi pi-bell',
        description: 'Alerts and unread platform updates',
        component: 'NotificationsSection',
    },
    activity: {
        key: 'activity',
        label: 'Activity',
        icon: 'pi pi-history',
        description: 'Chronological platform event timeline',
        component: 'ActivitySection',
    },
    reports: {
        key: 'reports',
        label: 'Reports',
        icon: 'pi pi-chart-bar',
        description: 'Exportable analytics and operational reports',
        component: 'ReportsSection',
    },
    roles: {
        key: 'roles',
        label: 'Roles',
        icon: 'pi pi-shield',
        description: 'User roles and permission matrix',
        component: 'RolesSection',
        adminRoute: '/admin/roles',
    },
    settings: {
        key: 'settings',
        label: 'Settings',
        icon: 'pi pi-cog',
        description: 'Dashboard preferences and platform configuration',
        component: 'SettingsSection',
    },
};

export const DASHBOARD_SECTION_LIST = Object.values(DASHBOARD_SECTIONS);
