import logoUrl from '@/assets/images/logo-dark.jpg';
import logoDataUri from '@/assets/images/logo-dark.jpg?inline';
import { downloadBlob } from '@/utils/downloadFile';
import { escapeHtml } from './htmlUtils';
import { renderDocumentPage } from './documentLayout';
import { renderListDocumentBody } from './renderListDocument';
import {
    renderContractDocumentPage as renderContractHtmlPage,
    renderContractSaleFooter,
    renderContractRentFooter,
} from './renderContractDocumentLayout';
import {
    renderContractDocumentBody,
    renderContractDocumentLead,
} from './renderContractDocument';
import {
    renderRentContractDocumentBody,
    renderRentContractDocumentLead,
} from './renderRentContractDocument';
import {
    getBillingDocumentMeta,
    renderUtilityDocumentBody,
    renderUtilityDocumentLead,
    renderPaymentDocumentBody,
    renderPaymentDocumentLead,
} from './renderBillingDocument';
import { renderInvoiceDocumentHtmlPage } from './renderInvoiceDocument';
import { renderReceiptDocumentHtmlPage } from './renderReceiptDocument';

function createBillingDocumentHandlers(renderPage) {
    return {
        print: (document) => printDocumentHtml(renderPage(document)),
        export: (document, filename) => {
            const html = renderPage(document);

            if (!exportDocumentHtml(html)) {
                // Export keeps HTML preview; downloads use the server PDF endpoints.
                downloadDocumentHtml(html, filename);
            }

            return true;
        },
    };
}

export { logoUrl as DOCUMENT_LOGO_URL };

const DOCUMENT_EXPORT_LOGO_SRC = logoDataUri;

export function renderContractDocumentPage(document) {
    const contractNo = document?.header?.contractNo || 'sale-contract';

    return renderContractHtmlPage({
        pageTitle: `Property Sale Agreement ${contractNo}`,
        documentTitle: 'Property Sale Agreement',
        contractNo,
        issueDate: document?.header?.issuedDate,
        leadHtml: renderContractDocumentLead(),
        bodyHtml: renderContractDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
        footerHtml: renderContractSaleFooter({ contractNo }),
    });
}

export function renderListDocumentPage({
    title,
    columns,
    rows,
    filters = [],
    generatedBy = 'Admin',
    landscape = true,
}) {
    const generatedAt = new Date().toLocaleString();
    const filterHtml = filters.length
        ? `<ul class="list-export-filters">${filters.map((filter) => `
            <li><strong>${escapeHtml(filter.label)}:</strong> ${escapeHtml(filter.value || 'All')}</li>
        `).join('')}</ul>`
        : '';

    const orientationClass = landscape ? 'pdf-sheet--list-landscape' : 'pdf-sheet--list-portrait';
    const page = renderDocumentPage({
        pageTitle: title,
        documentTitle: title,
        meta: [
            { label: 'Generated', value: generatedAt },
            { label: 'Generated By', value: generatedBy },
        ],
        bodyHtml: `${filterHtml}${renderListDocumentBody({ columns, rows })}`,
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
    });

    return page
        .replace('class="pdf-sheet"', `class="pdf-sheet ${orientationClass}"`)
        .replace(
            '<style>',
            `<style>
                @page { size: ${landscape ? 'A4 landscape' : 'A4 portrait'}; margin: 12mm; }
                .pdf-sheet--list-landscape { width: 297mm; max-width: 297mm; }
                .list-export-filters { margin: 0 0 1rem; padding: 0; list-style: none; font-size: 9pt; color: #6b6560; }
                .list-export-filters li { margin: 0.15rem 0; }
                .doc-table thead { display: table-header-group; }
                .doc-table tr { break-inside: avoid; page-break-inside: avoid; }
                @media print {
                    body { background: #fff !important; }
                    .pdf-sheet { box-shadow: none !important; border: none !important; margin: 0 !important; }
                }
            `,
        );
}

function openHtmlWindow(html, { print = false } = {}) {
    const printWindow = window.open('', '_blank');

    if (!printWindow) {
        return false;
    }

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();

    if (!print) {
        return true;
    }

    const closePrintWindow = () => {
        printWindow.close();
    };

    if ('onafterprint' in printWindow) {
        printWindow.onload = () => {
            printWindow.print();
            printWindow.onafterprint = closePrintWindow;
        };
    } else {
        printWindow.onload = () => {
            printWindow.print();
            window.setTimeout(closePrintWindow, 500);
        };
    }

    return true;
}

export function printDocumentHtml(html) {
    return openHtmlWindow(html, { print: true });
}

export function exportDocumentHtml(html) {
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const exportWindow = window.open(url, '_blank');

    if (!exportWindow) {
        return false;
    }

    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);

    return true;
}

export function downloadDocumentHtml(html, filename) {
    downloadBlob(
        filename,
        new Blob([html], { type: 'text/html;charset=utf-8' }),
    );
}

export function printContractDocument(document) {
    return printDocumentHtml(renderContractDocumentPage(document));
}

export function exportContractDocument(document, filename) {
    const html = renderContractDocumentPage(document);

    if (!exportDocumentHtml(html)) {
        downloadDocumentHtml(html, filename);
    }

    return true;
}

export function renderRentContractDocumentPage(document) {
    const contractNo = document?.header?.contractNo || 'rent-contract';

    return renderContractHtmlPage({
        pageTitle: `Property Rent Agreement ${contractNo}`,
        documentTitle: 'Property Rent Agreement',
        contractNo,
        issueDate: document?.header?.issuedDate,
        leadHtml: renderRentContractDocumentLead(),
        bodyHtml: renderRentContractDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
        footerHtml: renderContractRentFooter({ contractNo }),
    });
}

export function printRentContractDocument(document) {
    return printDocumentHtml(renderRentContractDocumentPage(document));
}

export function exportRentContractDocument(document, filename) {
    const html = renderRentContractDocumentPage(document);

    if (!exportDocumentHtml(html)) {
        downloadDocumentHtml(html, filename);
    }

    return true;
}

export function renderInvoiceDocumentPage(document) {
    return renderInvoiceDocumentHtmlPage(document, DOCUMENT_EXPORT_LOGO_SRC);
}

export function renderReceiptDocumentPage(document) {
    return renderReceiptDocumentHtmlPage(document, DOCUMENT_EXPORT_LOGO_SRC);
}

const invoiceDocumentHandlers = createBillingDocumentHandlers(renderInvoiceDocumentPage);
const receiptDocumentHandlers = createBillingDocumentHandlers(renderReceiptDocumentPage);

export function printInvoiceDocument(document) {
    return invoiceDocumentHandlers.print(document);
}

export function exportInvoiceDocument(document, filename) {
    return invoiceDocumentHandlers.export(document, filename);
}

export function printReceiptDocument(document) {
    return receiptDocumentHandlers.print(document);
}

export function exportReceiptDocument(document, filename) {
    return receiptDocumentHandlers.export(document, filename);
}

export function renderUtilityDocumentPage(document) {
    const referenceNo = document?.header?.referenceNo || 'utility-bill';

    return renderDocumentPage({
        pageTitle: `Utility Bill ${referenceNo}`,
        documentTitle: 'Utility Bill',
        meta: getBillingDocumentMeta(document, 'Bill No.'),
        leadHtml: renderUtilityDocumentLead(),
        bodyHtml: renderUtilityDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
    });
}

export function renderPaymentDocumentPage(document) {
    const referenceNo = document?.header?.referenceNo || 'payment';

    return renderDocumentPage({
        pageTitle: `Payment Confirmation ${referenceNo}`,
        documentTitle: 'Payment Confirmation',
        meta: getBillingDocumentMeta(document, 'Payment Ref.'),
        leadHtml: renderPaymentDocumentLead(),
        bodyHtml: renderPaymentDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
    });
}

const utilityDocumentHandlers = createBillingDocumentHandlers(renderUtilityDocumentPage);
const paymentDocumentHandlers = createBillingDocumentHandlers(renderPaymentDocumentPage);

export function printUtilityDocument(document) {
    return utilityDocumentHandlers.print(document);
}

export function exportUtilityDocument(document, filename) {
    return utilityDocumentHandlers.export(document, filename);
}

export function printPaymentDocument(document) {
    return paymentDocumentHandlers.print(document);
}

export function exportPaymentDocument(document, filename) {
    return paymentDocumentHandlers.export(document, filename);
}

export function printListDocument({
    title,
    columns,
    rows,
    filters = [],
    generatedBy = 'Admin',
    landscape = true,
}) {
    return printDocumentHtml(renderListDocumentPage({
        title,
        columns,
        rows,
        filters,
        generatedBy,
        landscape,
    }));
}
