import logoUrl from '@/assets/images/logo-dark.jpg';
import logoDataUri from '@/assets/images/logo-dark.jpg?inline';
import api from '@/libs/axios';
import { endpoint } from '@/services/endpoint';
import { downloadBlob } from '@/utils/downloadFile';
import { downloadPdfResponse, PDF_DOWNLOAD_HEADERS } from '@/utils/downloadPdfResponse';
import { escapeHtml } from './htmlUtils';
import { renderDocumentPage } from './documentLayout';
import { renderListDocumentBody } from './renderListDocument';
import {
    renderContractDocumentPage as renderContractHtmlPage,
    renderContractSaleFooter,
    renderContractRentFooter,
} from './renderContractDocumentLayout';
import {
    renderContractDocumentBody,
    renderContractDocumentLead,
} from './renderContractDocument';
import {
    renderRentContractDocumentBody,
    renderRentContractDocumentLead,
} from './renderRentContractDocument';
import {
    getBillingDocumentMeta,
    renderUtilityDocumentBody,
    renderUtilityDocumentLead,
    renderPaymentDocumentBody,
    renderPaymentDocumentLead,
} from './renderBillingDocument';
import { renderReceiptDocumentHtmlPage } from './renderReceiptDocument';
import {
    downloadSaleContractDocx,
    downloadRentContractDocx,
} from './contractDocxExport';

function createBillingDocumentHandlers(renderPage) {
    return {
        print: (document) => printDocumentHtml(renderPage(document)),
        export: (document, filename) => {
            const html = renderPage(document);

            if (!exportDocumentHtml(html)) {
                // Export keeps HTML preview; downloads use the server PDF endpoints.
                downloadDocumentHtml(html, filename);
            }

            return true;
        },
    };
}

export { logoUrl as DOCUMENT_LOGO_URL };

const DOCUMENT_EXPORT_LOGO_SRC = logoDataUri;

export function renderContractDocumentPage(document) {
    const contractNo = document?.header?.contractNo || 'sale-contract';

    return renderContractHtmlPage({
        pageTitle: `Property Sale Agreement ${contractNo}`,
        documentTitle: 'Property Sale Agreement',
        contractNo,
        issueDate: document?.header?.issuedDate,
        leadHtml: renderContractDocumentLead(),
        bodyHtml: renderContractDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
        footerHtml: renderContractSaleFooter({ contractNo }),
    });
}

function cleanContractPdfFilename(document, type) {
    const label = type === 'rent' ? 'Rent' : 'Sale';
    const prefix = type === 'rent' ? 'R' : 'S';
    const contractNo = document?.header?.contractNo || `${prefix}-000000`;

    return `Rosewood_Royale_${label}_Contract_${contractNo}.pdf`;
}

async function downloadPreviewPdf(html, filename) {
    const response = await api.post(
        endpoint.documentPreviewPdf,
        { html, filename },
        {
            responseType: 'blob',
            headers: PDF_DOWNLOAD_HEADERS,
        },
    );

    return downloadPdfResponse(response, filename);
}

export function downloadContractDocumentPdf(document) {
    return downloadPreviewPdf(
        renderContractDocumentPage(document),
        cleanContractPdfFilename(document, 'sale'),
    );
}

export function renderListDocumentPage({
    title,
    columns,
    rows,
    filters = [],
    generatedBy = 'Admin',
    landscape = true,
}) {
    const generatedAt = new Date().toLocaleString();
    const filterHtml = filters.length
        ? `<ul class="list-export-filters">${filters.map((filter) => `
            <li><strong>${escapeHtml(filter.label)}:</strong> ${escapeHtml(filter.value || 'All')}</li>
        `).join('')}</ul>`
        : '';

    const orientationClass = landscape ? 'pdf-sheet--list-landscape' : 'pdf-sheet--list-portrait';
    const page = renderDocumentPage({
        pageTitle: title,
        documentTitle: title,
        meta: [
            { label: 'Generated', value: generatedAt },
            { label: 'Generated By', value: generatedBy },
        ],
        bodyHtml: `${filterHtml}${renderListDocumentBody({ columns, rows })}`,
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
    });

    return page
        .replace('class="pdf-sheet"', `class="pdf-sheet ${orientationClass}"`)
        .replace(
            '<style>',
            `<style>
                @page { size: ${landscape ? 'A4 landscape' : 'A4 portrait'}; margin: 12mm; }
                .pdf-sheet--list-landscape { width: 297mm; max-width: 297mm; }
                .list-export-filters { margin: 0 0 1rem; padding: 0; list-style: none; font-size: 9pt; color: #6b6560; }
                .list-export-filters li { margin: 0.15rem 0; }
                .doc-table thead { display: table-header-group; }
                .doc-table tr { break-inside: avoid; page-break-inside: avoid; }
                @media print {
                    body { background: #fff !important; }
                    .pdf-sheet { box-shadow: none !important; border: none !important; margin: 0 !important; }
                }
            `,
        );
}

function openHtmlWindow(html, { print = false } = {}) {
    const printWindow = window.open('', '_blank');

    if (!printWindow) {
        return false;
    }

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();

    if (!print) {
        return true;
    }

    const closePrintWindow = () => {
        printWindow.close();
    };

    if ('onafterprint' in printWindow) {
        printWindow.onload = () => {
            printWindow.print();
            printWindow.onafterprint = closePrintWindow;
        };
    } else {
        printWindow.onload = () => {
            printWindow.print();
            window.setTimeout(closePrintWindow, 500);
        };
    }

    return true;
}

export function printDocumentHtml(html) {
    return openHtmlWindow(html, { print: true });
}

export function exportDocumentHtml(html) {
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const exportWindow = window.open(url, '_blank');

    if (!exportWindow) {
        return false;
    }

    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);

    return true;
}

export function downloadDocumentHtml(html, filename) {
    downloadBlob(
        filename,
        new Blob([html], { type: 'text/html;charset=utf-8' }),
    );
}

export function printContractDocument(document) {
    return printDocumentHtml(renderContractDocumentPage(document));
}

export function viewContractDocument(document) {
    return exportDocumentHtml(renderContractDocumentPage(document));
}

export function exportContractDocument(document) {
    downloadSaleContractDocx(document);

    return true;
}

export function renderRentContractDocumentPage(document) {
    const contractNo = document?.header?.contractNo || 'rent-contract';

    return renderContractHtmlPage({
        pageTitle: `Rental/Lease Agreement ${contractNo}`,
        documentTitle: 'Rental/Lease Agreement',
        contractNo,
        issueDate: document?.header?.issuedDate,
        leadHtml: renderRentContractDocumentLead(),
        bodyHtml: renderRentContractDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
        footerHtml: renderContractRentFooter({ contractNo }),
    });
}

export function downloadRentContractDocumentPdf(document) {
    return downloadPreviewPdf(
        renderRentContractDocumentPage(document),
        cleanContractPdfFilename(document, 'rent'),
    );
}

export function printRentContractDocument(document) {
    return printDocumentHtml(renderRentContractDocumentPage(document));
}

export function viewRentContractDocument(document) {
    return exportDocumentHtml(renderRentContractDocumentPage(document));
}

export function exportRentContractDocument(document) {
    downloadRentContractDocx(document);

    return true;
}

export function renderReceiptDocumentPage(document) {
    return renderReceiptDocumentHtmlPage(document, DOCUMENT_EXPORT_LOGO_SRC);
}

const receiptDocumentHandlers = createBillingDocumentHandlers(renderReceiptDocumentPage);

export function printReceiptDocument(document) {
    return receiptDocumentHandlers.print(document);
}

export function viewReceiptDocument(document) {
    return exportDocumentHtml(renderReceiptDocumentPage(document));
}

export function exportReceiptDocument(document, filename) {
    return receiptDocumentHandlers.export(document, filename);
}

export function renderUtilityDocumentPage(document) {
    const referenceNo = document?.header?.referenceNo || 'utility-bill';

    return renderDocumentPage({
        pageTitle: `Utility Bill ${referenceNo}`,
        documentTitle: 'Utility Bill',
        meta: getBillingDocumentMeta(document, 'Bill No.'),
        leadHtml: renderUtilityDocumentLead(),
        bodyHtml: renderUtilityDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
    });
}

export function downloadUtilityDocumentPdf(document) {
    const referenceNo = document?.header?.referenceNo || 'utility-bill';

    return downloadPreviewPdf(
        renderUtilityDocumentPage(document),
        `${referenceNo}.pdf`,
    );
}

export function renderPaymentDocumentPage(document) {
    const referenceNo = document?.header?.referenceNo || 'payment';

    return renderDocumentPage({
        pageTitle: `Payment Confirmation ${referenceNo}`,
        documentTitle: 'Payment Confirmation',
        meta: getBillingDocumentMeta(document, 'Payment Ref.'),
        leadHtml: renderPaymentDocumentLead(),
        bodyHtml: renderPaymentDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
    });
}

const utilityDocumentHandlers = createBillingDocumentHandlers(renderUtilityDocumentPage);
const paymentDocumentHandlers = createBillingDocumentHandlers(renderPaymentDocumentPage);

export function printUtilityDocument(document) {
    return utilityDocumentHandlers.print(document);
}

export function viewUtilityDocument(document) {
    return exportDocumentHtml(renderUtilityDocumentPage(document));
}

export function exportUtilityDocument(document, filename) {
    return utilityDocumentHandlers.export(document, filename);
}

export function printPaymentDocument(document) {
    return paymentDocumentHandlers.print(document);
}

export function exportPaymentDocument(document, filename) {
    return paymentDocumentHandlers.export(document, filename);
}

export function printListDocument({
    title,
    columns,
    rows,
    filters = [],
    generatedBy = 'Admin',
    landscape = true,
}) {
    return printDocumentHtml(renderListDocumentPage({
        title,
        columns,
        rows,
        filters,
        generatedBy,
        landscape,
    }));
}
