import logoUrl from '@/assets/images/logo-dark.jpg';
import logoDataUri from '@/assets/images/logo-dark.jpg?inline';
import api from '@/libs/axios';
import { endpoint } from '@/services/endpoint';
import { downloadBlob } from '@/utils/downloadFile';
import { downloadPdfResponse, PDF_DOWNLOAD_HEADERS } from '@/utils/downloadPdfResponse';
import { formatProjectDateTime } from '@/utils/timezone';
import { escapeHtml } from './htmlUtils';
import { renderDocumentPage } from './documentLayout';
import { renderListDocumentBody } from './renderListDocument';
import {
    renderContractDocumentPage as renderContractHtmlPage,
    renderContractSaleFooter,
    renderContractRentFooter,
} from './renderContractDocumentLayout';
import {
    renderContractDocumentBody,
    renderContractDocumentLead,
} from './renderContractDocument';
import {
    renderRentContractDocumentBody,
    renderRentContractDocumentLead,
} from './renderRentContractDocument';
import {
    getBillingDocumentMeta,
    renderUtilityDocumentBody,
    renderUtilityDocumentLead,
} from './renderBillingDocument';
import { renderReceiptDocumentHtmlPage } from './renderReceiptDocument';
import {
    downloadSaleContractDocx,
    downloadRentContractDocx,
} from './contractDocxExport';

function createBillingDocumentHandlers(renderPage) {
    return {
        print: (document) => printDocumentHtml(renderPage(document)),
        export: (document, filename) => {
            const html = renderPage(document);

            if (!exportDocumentHtml(html)) {
                // Export keeps HTML preview; downloads use the server PDF endpoints.
                downloadDocumentHtml(html, filename);
            }

            return true;
        },
    };
}

export { logoUrl as DOCUMENT_LOGO_URL };

const DOCUMENT_EXPORT_LOGO_SRC = logoDataUri;

export function renderContractDocumentPage(document) {
    const contractNo = document?.header?.contractNo || 'sale-contract';

    return renderContractHtmlPage({
        pageTitle: `Property Sale Agreement ${contractNo}`,
        documentTitle: 'Property Sale Agreement',
        contractNo,
        issueDate: document?.header?.issuedDate,
        leadHtml: renderContractDocumentLead(),
        bodyHtml: renderContractDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
        footerHtml: renderContractSaleFooter({ contractNo }),
    });
}

function cleanContractPdfFilename(document, type) {
    const prefix = type === 'rent' ? 'R' : 'S';
    const contractNo = document?.header?.contractNo || `${prefix}-000000`;

    return `${contractNo}.pdf`;
}

async function downloadPreviewPdf(html, filename) {
    const response = await api.post(
        endpoint.documentPreviewPdf,
        { html, filename },
        {
            responseType: 'blob',
            headers: PDF_DOWNLOAD_HEADERS,
        },
    );

    return downloadPdfResponse(response, filename);
}

export function downloadContractDocumentPdf(document) {
    return downloadPreviewPdf(
        renderContractDocumentPage(document),
        cleanContractPdfFilename(document, 'sale'),
    );
}

export function renderListDocumentPage({
    title,
    columns,
    rows,
    filters = [],
    generatedBy = 'Admin',
    landscape = true,
}) {
    const generatedAt = formatProjectDateTime(new Date());
    const filterHtml = filters.length
        ? `<ul class="list-export-filters">${filters.map((filter) => `
            <li><strong>${escapeHtml(filter.label)}:</strong> ${escapeHtml(filter.value || 'All')}</li>
        `).join('')}</ul>`
        : '';

    const orientationClass = landscape ? 'pdf-sheet--list-landscape' : 'pdf-sheet--list-portrait';
    const page = renderDocumentPage({
        pageTitle: title,
        documentTitle: title,
        meta: [
            { label: 'Generated', value: generatedAt },
            { label: 'Generated By', value: generatedBy },
        ],
        bodyHtml: `${filterHtml}${renderListDocumentBody({ columns, rows })}`,
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
        footerRightText: 'Rosewood Royale',
    });

    return page
        .replace('class="pdf-sheet"', `class="pdf-sheet pdf-sheet--list ${orientationClass}"`)
        .replace(
            '<style>',
            `<style>
                @page { size: ${landscape ? 'A4 landscape' : 'A4 portrait'}; margin: 8mm 8mm 12mm 8mm; }
                .pdf-sheet.pdf-sheet--list {
                    width: 100% !important;
                    max-width: none !important;
                    min-height: 0 !important;
                    margin: 0 !important;
                    padding: 0 !important;
                    border: none !important;
                    box-shadow: none !important;
                    overflow-wrap: break-word;
                    font-size: 10pt;
                    line-height: 1.35;
                }
                .pdf-sheet--list .pdf-head { margin-bottom: 0.45rem; }
                .pdf-sheet--list .pdf-head-row { gap: 0.75rem; margin-bottom: 0.4rem; }
                .pdf-sheet--list .pdf-logo { width: 1.65rem; height: 1.65rem; }
                .pdf-sheet--list .pdf-brand { gap: 0.65rem; }
                .pdf-sheet--list .pdf-company { font-size: 9pt; letter-spacing: 0.1em; }
                .pdf-sheet--list .pdf-company-sub { margin-top: 0.1rem; font-size: 7pt; }
                .pdf-sheet--list .pdf-meta-item { margin-bottom: 0.25rem; gap: 0.05rem; }
                .pdf-sheet--list .pdf-meta-label { font-size: 6pt; letter-spacing: 0.12em; }
                .pdf-sheet--list .pdf-meta-value { font-size: 8pt; }
                .pdf-sheet--list .pdf-doc-title { margin: 0; font-size: 12pt; letter-spacing: 0.12em; }
                .pdf-sheet--list .pdf-rule--accent { width: 3rem; margin: 0.3rem auto 0; }
                .list-export-filters {
                    display: grid;
                    grid-template-columns: repeat(2, minmax(0, 1fr));
                    column-gap: 1.25rem;
                    row-gap: 0.15rem;
                    margin: 0.4rem 0 0.55rem;
                    padding: 0;
                    list-style: none;
                    font-size: 7.5pt;
                    line-height: 1.3;
                    color: #6b6560;
                }
                .list-export-filters li { margin: 0; min-width: 0; }
                .list-export-filters strong { color: #1c1c1c; font-weight: 600; }
                .pdf-sheet--list .pdf-block { margin-bottom: 0; }
                .pdf-sheet--list .doc-table-wrap { margin-top: 0; overflow: visible; }
                .pdf-sheet--list .doc-table {
                    width: 100% !important;
                    table-layout: fixed;
                    border-collapse: collapse;
                    font-size: 9pt;
                }
                .pdf-sheet--list .doc-table th,
                .pdf-sheet--list .doc-table td {
                    border: none;
                    border-bottom: 1px solid rgba(28, 28, 28, 0.12);
                    padding: 5px 9px;
                    vertical-align: top;
                    text-align: left;
                    overflow-wrap: break-word;
                    word-break: normal;
                    box-sizing: border-box;
                }
                .pdf-sheet--list .doc-table th {
                    background: rgba(122, 49, 73, 0.07);
                    border-bottom: 1px solid rgba(122, 49, 73, 0.22);
                    font-size: 7.5pt;
                    font-weight: 600;
                    letter-spacing: 0.04em;
                    text-transform: uppercase;
                    color: #5c3d47;
                    padding-top: 6px;
                    padding-bottom: 6px;
                }
                .list-col--align-center { text-align: center; }
                .list-col--align-right { text-align: right; }
                .list-col--nowrap { white-space: nowrap; overflow-wrap: normal; word-break: keep-all; overflow: hidden; }
                .list-col--issued_date,
                .list-col--due_date,
                .list-col--payment_status,
                .list-col--status,
                .list-col--payment_date,
                .list-col--date,
                .list-col--created_at { padding-left: 11px; padding-right: 11px; }
                .doc-table thead { display: table-header-group; }
                .doc-table tr { break-inside: avoid; page-break-inside: avoid; }
                @media print {
                    html { counter-reset: none; }
                    body { background: #fff !important; }
                    .pdf-sheet { box-shadow: none !important; border: none !important; margin: 0 !important; }
                    .pdf-sheet--list .pdf-foot-page { font-size: 0; }
                    .pdf-sheet--list .pdf-foot-page::after {
                        content: 'Page ' counter(page);
                        font-size: 7pt;
                        letter-spacing: 0.08em;
                        text-transform: none;
                        color: #6b6560;
                    }
                }
            `,
        );
}

function openHtmlWindow(html, { print = false } = {}) {
    const printWindow = window.open('', '_blank');

    if (!printWindow) {
        return false;
    }

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();

    if (!print) {
        return true;
    }

    const closePrintWindow = () => {
        printWindow.close();
    };

    if ('onafterprint' in printWindow) {
        printWindow.onload = () => {
            printWindow.print();
            printWindow.onafterprint = closePrintWindow;
        };
    } else {
        printWindow.onload = () => {
            printWindow.print();
            window.setTimeout(closePrintWindow, 500);
        };
    }

    return true;
}

export function printDocumentHtml(html) {
    return openHtmlWindow(html, { print: true });
}

export function exportDocumentHtml(html) {
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const exportWindow = window.open(url, '_blank');

    if (!exportWindow) {
        return false;
    }

    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);

    return true;
}

export function downloadDocumentHtml(html, filename) {
    downloadBlob(
        filename,
        new Blob([html], { type: 'text/html;charset=utf-8' }),
    );
}

export function printContractDocument(document) {
    return printDocumentHtml(renderContractDocumentPage(document));
}

export function viewContractDocument(document) {
    return exportDocumentHtml(renderContractDocumentPage(document));
}

export function exportContractDocument(document) {
    downloadSaleContractDocx(document);

    return true;
}

export function renderRentContractDocumentPage(document) {
    const contractNo = document?.header?.contractNo || 'rent-contract';

    return renderContractHtmlPage({
        pageTitle: `Rental/Lease Agreement ${contractNo}`,
        documentTitle: 'Rental/Lease Agreement',
        contractNo,
        issueDate: document?.header?.issuedDate,
        leadHtml: renderRentContractDocumentLead(),
        bodyHtml: renderRentContractDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
        footerHtml: renderContractRentFooter({ contractNo }),
    });
}

export function downloadRentContractDocumentPdf(document) {
    return downloadPreviewPdf(
        renderRentContractDocumentPage(document),
        cleanContractPdfFilename(document, 'rent'),
    );
}

export function printRentContractDocument(document) {
    return printDocumentHtml(renderRentContractDocumentPage(document));
}

export function viewRentContractDocument(document) {
    return exportDocumentHtml(renderRentContractDocumentPage(document));
}

export function exportRentContractDocument(document) {
    downloadRentContractDocx(document);

    return true;
}

export function renderReceiptDocumentPage(document) {
    return renderReceiptDocumentHtmlPage(document, DOCUMENT_EXPORT_LOGO_SRC);
}

const receiptDocumentHandlers = createBillingDocumentHandlers(renderReceiptDocumentPage);

export function printReceiptDocument(document) {
    return receiptDocumentHandlers.print(document);
}

export function viewReceiptDocument(document) {
    return exportDocumentHtml(renderReceiptDocumentPage(document));
}

export function exportReceiptDocument(document, filename) {
    return receiptDocumentHandlers.export(document, filename);
}

export function renderUtilityDocumentPage(document) {
    const referenceNo = document?.header?.referenceNo || 'utility-bill';

    return renderDocumentPage({
        pageTitle: `Utility Bill ${referenceNo}`,
        documentTitle: 'Utility Bill',
        meta: getBillingDocumentMeta(document, 'Bill No.'),
        leadHtml: renderUtilityDocumentLead(),
        bodyHtml: renderUtilityDocumentBody(document),
        logoSrc: DOCUMENT_EXPORT_LOGO_SRC,
    });
}

export function downloadUtilityDocumentPdf(document) {
    const id = document?.id;
    const referenceNo = typeof id === 'number' || (typeof id === 'string' && id !== '')
        ? `UTL-${String(id).padStart(6, '0')}`
        : (document?.header?.referenceNo || 'UTL-000000');

    return downloadPreviewPdf(
        renderUtilityDocumentPage(document),
        `${referenceNo}.pdf`,
    );
}

const utilityDocumentHandlers = createBillingDocumentHandlers(renderUtilityDocumentPage);

export function printUtilityDocument(document) {
    return utilityDocumentHandlers.print(document);
}

export function viewUtilityDocument(document) {
    return exportDocumentHtml(renderUtilityDocumentPage(document));
}

export function exportUtilityDocument(document, filename) {
    return utilityDocumentHandlers.export(document, filename);
}

export function printListDocument({
    title,
    columns,
    rows,
    filters = [],
    generatedBy = 'Admin',
    landscape = true,
}) {
    return printDocumentHtml(renderListDocumentPage({
        title,
        columns,
        rows,
        filters,
        generatedBy,
        landscape,
    }));
}
